-- City Content Table for SEO
create table city_content (
  id bigint generated by default as identity primary key,
  city text not null,
  state text not null,
  intro_text text,
  meta_title text,
  meta_description text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(city, state)
);

-- Enable RLS
alter table city_content enable row level security;

-- Allow public read
create policy "Allow public read access" on city_content for select using (true);
create policy "Allow service role full access" on city_content for all using (true);
