-- ⚠️ RESET SCRIPT: Drops and recreates the agent_logs table
-- Run this in Supabase SQL Editor to fix the "column does not exist" error.

DROP TABLE IF EXISTS agent_logs;

CREATE TABLE agent_logs (
  id bigint generated by default as identity primary key,
  agent_name text not null,
  action_type text not null,
  details jsonb,
  status text not null check (status in ('success', 'error', 'warning')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Re-create indexes
CREATE INDEX agent_logs_created_at_idx ON agent_logs (created_at desc);
CREATE INDEX agent_logs_agent_name_idx ON agent_logs (agent_name);

-- Verify it works by inserting a dummy log
INSERT INTO agent_logs (agent_name, action_type, status, details)
VALUES ('System', 'initialization', 'success', '{"msg": "Table created successfully"}');
