-- Agent Logs Table
create table agent_logs (
  id bigint generated by default as identity primary key,
  agent_id text not null,
  action text not null,
  message text not null,
  status text not null, -- 'success', 'warning', 'error'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (optional, but good practice)
alter table agent_logs enable row level security;

-- Allow public read (for dashboard) and service role write
create policy "Allow public read access" on agent_logs for select using (true);
create policy "Allow service role insert" on agent_logs for insert with check (true);
