-- Installers Table
create table installers (
  id bigint generated by default as identity primary key,
  business_name text not null,
  license_number text,
  phone text,
  city text not null,
  state text not null,
  zip_code text not null,
  utility_provider text,
  services text,
  verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Locations Table (for programmatic pages)
create table locations (
  id bigint generated by default as identity primary key,
  city text not null,
  state text not null,
  zip_code text not null,
  slug text not null unique, -- e.g., "tx/austin"
  population integer,
  avg_kwh_price numeric,
  installer_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for fast lookup
create index installers_city_idx on installers (city);
create index installers_zip_idx on installers (zip_code);
create index locations_slug_idx on locations (slug);
