-- Create Leads Table for Angi Capture
create table if not exists leads (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  zip_code text not null,
  project_type text, -- 'install', 'repair'
  details text,
  city text,
  state text,
  source text default 'website_form',
  status text default 'new', -- 'new', 'sent_to_angi', 'error'
  angi_lead_id text, -- ID returned from Angi API
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table leads enable row level security;

-- Allow inserts from anon (public form)
create policy "Allow public inserts" on leads
  for insert with check (true);

-- Allow read only for service_role (admin)
create policy "Allow service_role read" on leads
  for select using (true);
