-- Ensure city_content table exists
create table if not exists city_content (
  id bigint generated by default as identity primary key,
  city_slug text not null,
  state_slug text not null,
  intro_text text,
  meta_title text,
  meta_description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(city_slug, state_slug)
);

-- Add new columns for Full Page Content
alter table city_content 
add column if not exists faqs jsonb default '[]'::jsonb,
add column if not exists rebates_info text,
add column if not exists why_hire_text text;

-- Enable RLS
alter table city_content enable row level security;

-- Allow public read
create policy "Allow public read" on city_content
  for select using (true);

-- Allow service role write
create policy "Allow service role write" on city_content
  for all using (true);
